package com.minecolonies.kingdoms.world.settlement.layout;

public enum LayoutRejectionReason
{
    WATER,
    DISALLOWED_BIOME,
    SLOPE,
    CLIFF,
    ROUGHNESS,
    EXCESSIVE_CUT,
    EXCESSIVE_FILL,
    EXCESSIVE_TERRAIN_VOLUME,
    RETAINING_WALL,
    SAMPLE_LIMIT,
    UNSUPPORTED_FOOTPRINT,
    STARTER_EXCLUSION,
    GATE_APPROACH,
    BUILDING_COLLISION,
    GLOBAL_ROAD,
    LOCAL_STREET_COLLISION,
    STREET_UNREACHABLE,
    OUTSIDE_RADIUS,
    SEARCH_BUDGET,
    UNLOADED_TERRAIN,
    NO_STRUCTURE,
    NO_VALID_ROTATION
}
